# -*- coding: utf-8 -*-
"""Credit Card Fraud Dete ction System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuZl1R2CC12TbzoWdIePIoXlRKon8s2Z
"""

!pip install kagglehub plotly --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import kagglehub
import warnings
warnings.filterwarnings("ignore")

path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

csv_path = path + "/creditcard.csv"

df = pd.read_csv(csv_path)

display(df.head())

print(df.shape)
print(df.info())
print(df.isnull().sum())

df = df.drop_duplicates()

display(df.describe())

fraud_count = df['Class'].value_counts()

print(fraud_count)

plt.figure(figsize=(6,5))
sns.countplot(x='Class', data=df)
plt.title("Fraud vs Normal Transactions")
plt.show()

plt.figure(figsize=(10,5))
plt.hist(df['Amount'], bins=50)
plt.title("Transaction Amount Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Amount'])
plt.title("Boxplot of Transaction Amount")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Class', y='Amount', data=df)
plt.title("Fraud vs Transaction Amount")
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(df['Time'], df['Amount'], alpha=0.5)
plt.title("Time vs Amount")
plt.xlabel("Time")
plt.ylabel("Amount")
plt.show()

plt.figure(figsize=(18,12))
correlation = df.corr()
sns.heatmap(correlation, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

def risk_level(amount):

    if amount < 100:
        return "Low Risk"

    elif amount < 1000:
        return "Medium Risk"

    else:
        return "High Risk"

df['Risk_Level'] = df['Amount'].apply(risk_level)

print(df['Risk_Level'].value_counts())

plt.figure(figsize=(7,5))
sns.countplot(x='Risk_Level', data=df)
plt.title("Risk Level Distribution")
plt.show()

X = df[['Time']]
y = df['Amount']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:10])

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R2 Score:", r2)
print("Mean Squared Error:", mse)

plt.figure(figsize=(10,5))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Actual Amount")
plt.ylabel("Predicted Amount")
plt.title("Actual vs Predicted Amount")
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(10,5))
plt.scatter(y_pred, residuals, alpha=0.5)
plt.axhline(y=0)
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Analysis")
plt.show()

fig1 = px.pie(
    names=['Normal', 'Fraud'],
    values=fraud_count.values,
    title='Fraud vs Normal Transactions'
)

fig1.show()

fig2 = px.histogram(
    df,
    x='Amount',
    nbins=50,
    title='Transaction Amount Distribution'
)

fig2.show()

fig3 = px.scatter(
    df.sample(5000),
    x='Time',
    y='Amount',
    color='Class',
    title='Time vs Amount'
)

fig3.show()

fig4 = px.bar(
    df['Risk_Level'].value_counts(),
    title='Risk Level Distribution'
)

fig4.show()

high_risk_fraud = df[
    (df['Class'] == 1) &
    (df['Risk_Level'] == 'High Risk')
]

display(high_risk_fraud.head())

print("Total Transactions:", len(df))
print("Fraud Transactions:", len(df[df['Class'] == 1]))
print("Normal Transactions:", len(df[df['Class'] == 0]))
print("Average Transaction Amount:", round(df['Amount'].mean(), 2))
print("Maximum Transaction Amount:", df['Amount'].max())
print("Minimum Transaction Amount:", df['Amount'].min())

df.to_csv("cleaned_creditcard_dataset.csv", index=False)

from google.colab import files

files.download("cleaned_creditcard_dataset.csv")